# application.properties 파일은 항상 resource 폴더 바로 아래에 만든다.
# 목적 : 스프링 서버가 실행될 때 설정을 로딩하는 파일
# 주석은 #을 사용.
# 참고 : 상단 메뉴 -> 설정 -> 파일 인코딩 -> 프로퍼티 파일의 대한 디폴트 인코딩 : UTF-8로 변경

# 1. 내장 WAS PORT 번호 변경
sever.port = 8080

# 2. DAO 가 아닌 프로퍼티 파일에서 DB 연동이 가능하다. JDBC
# 2-1 연동할 db서버의 주소
# spring.datasource.url= jdbc:mysql://localhost:3306/practice6
# spring.datasource.url= jdbc:mysql://localhost:3306/boardservice10
#spring.datasource.url= jdbc:mysql://localhost:3306/practice2

# 2-2 연동할 db서버의 계정
spring.datasource.username = root
spring.datasource.password = 1234


# 2-3 Entity 테이블 생성(none 으로 하면 DB에서 무조건 만들어야하고 update 이면 굳이 DB에서 만들 필요까지는 없음)
spring.jpa.hibernate.ddl-auto= create

# 2-4 콘솔창에 실행된 sql 표시
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL 내 매개변수 값들을 표시 *운영/배포 시 모니터링(유지보수) 사용되는 경우 *
logging.level.org.hibernate.orm.jdbc.bind = TRACE
logging.level.org.hibernate.sql = DEBUG

# 2-5 서버 실행할때 SQL 파일 실행 *개발단계*(개발단계에서만 쓰고 완성후에 none 또는 주석처리),     always,none
#spring.sql.init.mode = always

# 2-6 서버 실행할때 classpath(resources폴더) 이하 경로에 data.sql 파일경로 지정
spring.sql.init.data-locations=classpath:/sql/data.sql

# 2-7 서버 실행할때 JPA가 초기화하는 파일 실행
#spring.jpa.defer-datasource-initialization=true



# 2-3 ~ 2-7 번까지는 모니터링, 개발단계용